-- CREATE CUSTOMERS TABLE
CREATE TABLE CUSTOMERS (
    customerID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    firstName VARCHAR2(255) NOT NULL,
    lastName VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL,
    phone VARCHAR2(12) NOT NULL
);

-- CREATE APPLIANCES TABLE
CREATE TABLE APPLIANCES (
    applianceID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    applianceName VARCHAR2(255) NOT NULL,
    applianceType VARCHAR2(255) NOT NULL
);

-- CREATE CUST_APPLIANCES JUNCTION TABLE
CREATE TABLE CUST_APPLIANCES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    customerID NUMBER,
    applianceID NUMBER,
    CONSTRAINT FK_CUSTOMER_APPLIANCE FOREIGN KEY (applianceID) REFERENCES APPLIANCES(applianceID),
    CONSTRAINT FK_APPLIANCE_CUSTOMER FOREIGN KEY (customerID) REFERENCES CUSTOMERS(customerID)
);

-- CREATE TECHNICIANS TABLE
CREATE TABLE TECHNICIANS (
    technicianID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    firstName VARCHAR2(255) NOT NULL,
    lastName VARCHAR2(255) NOT NULL
);

-- CREATE APPOINTMENTS TABLE
CREATE TABLE APPOINTMENTS (
    appointmentID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    applianceID NUMBER,
    technicianID NUMBER,
    customerID NUMBER,
    appointmentDateTime TIMESTAMP NOT NULL,
    reason NVARCHAR2(500),
    quote DECIMAL(10,2),
    CONSTRAINT FK_APPOINTMENT_APPLIANCE FOREIGN KEY (applianceID) REFERENCES APPLIANCES(applianceID),
    CONSTRAINT FK_APPOINTMENT_TECHNICIAN FOREIGN KEY (technicianID) REFERENCES TECHNICIANS(technicianID),
    CONSTRAINT FK_APPOINTMENT_CUSTOMER FOREIGN KEY (customerID) REFERENCES CUSTOMERS(customerID)
);
